# Generated by Django 5.2.8 on 2025-11-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0003_remove_quarto_id_alter_quarto_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='quarto',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='quarto',
            name='descricao_detalhada',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='quartos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='servicos',
            field=models.ManyToManyField(related_name='quartos', to='quartos.servico'),
        ),
    ]
