# Generated by Django 5.2.8 on 2025-11-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0004_servico_quarto_avaliacao_quarto_descricao_detalhada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='disponibilidade',
        ),
    ]
