# Generated by Django 5.2.8 on 2025-11-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0005_remove_quarto_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos_adicionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='servicos',
        ),
        migrations.AddField(
            model_name='quarto',
            name='servicos_adicionais',
            field=models.ManyToManyField(blank=True, related_name='quartos', to='quartos.servicos_adicionais'),
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
