# Generated by Django 5.2.8 on 2025-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0007_delete_servicos_adicionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
