# Generated by Django 5.2.8 on 2025-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_hospede_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='uid_firebase',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
