# Generated by Django 5.2.8 on 2025-11-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0006_servicos_adicionais_remove_quarto_servicos_and_more'),
        ('servicos_adicionais', '0002_alter_servicos_adicionais_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicos_adicionais',
        ),
        migrations.AlterField(
            model_name='quarto',
            name='servicos_adicionais',
            field=models.ManyToManyField(blank=True, related_name='quartos', to='servicos_adicionais.servicos_adicionais'),
        ),
    ]
