# Generated by Django 5.2.8 on 2025-12-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0008_quarto_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='banheiros',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='camas',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
